#ifndef __DEFINITION_HEADER__
#define __DEFINITION_HEADER__

/***********************************/
/* このファイルではピン名の定義や、*/
/* パラメーター定義を行う。        */
/*				   */
/* ピンの使用用途によっては定義を、*/
/* そのたびに変更を加えていく　　　*/
/***********************************/


//GPIOピン名定義
#define P03 PORT0.PODR.BIT.B3
#define P05 PORT0.PODR.BIT.B5
#define P14 PORT1.PODR.BIT.B4
#define P15 PORT1.PODR.BIT.B5
#define P16 PORT1.PODR.BIT.B6
#define P17 PORT1.PODR.BIT.B7
#define P26 PORT2.PODR.BIT.B6
#define P27 PORT2.PODR.BIT.B7
#define P30 PORT3.PODR.BIT.B0
#define P31 PORT3.PODR.BIT.B1
#define P32 PORT3.PODR.BIT.B2
#define P35 PORT3.PODR.BIT.B5
#define P36 PORT3.PODR.BIT.B6
#define P37 PORT3.PODR.BIT.B7
#define P40 PORT4.PODR.BIT.B0
#define P41 PORT4.PODR.BIT.B1
#define P42 PORT4.PODR.BIT.B2
#define P43 PORT4.PODR.BIT.B3
#define P44 PORT4.PODR.BIT.B4
#define P46 PORT4.PODR.BIT.B6
#define P54 PORT5.PODR.BIT.B4
#define P55 PORT5.PODR.BIT.B5
#define PA0 PORTA.PODR.BIT.B0
#define PA1 PORTA.PODR.BIT.B1
#define PA3 PORTA.PODR.BIT.B3
#define PA4 PORTA.PODR.BIT.B4
#define PA6 PORTA.PODR.BIT.B6
#define PB0 PORTB.PODR.BIT.B0
#define PB1 PORTB.PODR.BIT.B1
#define PB3 PORTB.PODR.BIT.B3
#define PB5 PORTB.PODR.BIT.B5
#define PB6 PORTB.PODR.BIT.B6
#define PB7 PORTB.PODR.BIT.B7
#define PC2 PORTC.PODR.BIT.B2
#define PC3 PORTC.PODR.BIT.B3
#define PC4 PORTC.PODR.BIT.B4
#define PC5 PORTC.PODR.BIT.B5
#define PC6 PORTC.PODR.BIT.B6
#define PC7 PORTC.PODR.BIT.B7
#define PE0 PORTE.PODR.BIT.B0
#define PE1 PORTE.PODR.BIT.B1
#define PE2 PORTE.PODR.BIT.B2
#define PE3 PORTE.PODR.BIT.B3
#define PE4 PORTE.PODR.BIT.B4
#define PE5 PORTE.PODR.BIT.B5
#define PH0 PORTH.PODR.BIT.B0
#define PH1 PORTH.PODR.BIT.B1
#define PH2 PORTH.PODR.BIT.B2
#define PH3 PORTH.PODR.BIT.B3

#endif