#include "manabino_tonelib.h"
#include "ducktone.h"
//extern void tone(int, int, int);
//extern void noTone(int);
extern int canaflag;
void canada(void *pvParameters) {
  tempo(120);
  tone(A3, hf);
  tone(C4, qtb);
  tone(C4, et);
  tone(F3, hfb);
  tone(G3, qt);
  tone(A3, qt);
  tone(Bf3, qt);
  tone(C4, qt);
  tone(D4, qt);
  tone(G3, hfb);
  noTone();
  delay(qt);
  tone(A3, hf);
  tone(B3, qtb);
  tone(B3, et);
  tone(C4, hfb);
  tone(D4, qt);
  tone(E4, qt);
  tone(E4, qt);
  tone(D4, qt);
  tone(D4, qt);
  tone(C4, hfb);
  tone(G3, etb);
  tone(A3, st);
  tone(Bf3, qtb);
  tone(A3, et);
  tone(G3, qt);
  tone(A3, etb);
  tone(Bf3, st);
  tone(C4, qtb);
  tone(Bf3, et);
  tone(A3, qt);
  tone(Bf3, etb);
  tone(C4, st);
  tone(D4, qt);
  tone(C4, qt);
  tone(Bf3, qt);
  tone(A3, qt);
  tone(G3, hfb);
  tone(G3, etb);
  tone(A3, st);
  tone(Bf3, qtb);
  tone(A3, et);
  tone(G3, qt);
  tone(A3, etb);
  tone(Bf3, st);
  tone(C4, qtb);
  tone(Bf3, et);
  tone(A3, qt);
  tone(A3, qt);
  tone(G3, qt);
  tone(C4, qt);
  tone(C4, et);
  tone(B3, et);
  tone(A3, et);
  tone(B3, et);
  tone(C4, hf);
  noTone();
  delay(hf);
  tone(A3, hf);
  tone(C4, qtb);
  tone(C4, et);
  tone(F3, hf);
  noTone();
  delay(hf);
  tone(Bf3, hf);
  tone(D4, qtb);
  tone(D4, et);
  tone(G3, hf);
  noTone();
  delay(hf);
  tone(C4, hf);
  tone(Cs4, qtb);
  tone(Cs4, et);
  tone(D4, qt);
  tone(Bf3, qt);
  tone(A3, qt);
  tone(G3, qt);
  tone(F3, hf);
  tone(G3, hf);
  tone(A3, hfb);
  noTone();
  delay(qt);
  tone(C4, hf);
  tone(F4, qtb);
  tone(F4, et);
  tone(D4, qt);
  tone(Bf3, qt);
  tone(A3, qt);
  tone(G3, qt);
  tone(C4, hf);
  tone(E3, hf);
  tone(F3, hfb);
  noTone();
  delay(qt);
  //while (1);
  canaflag = 1;
  vTaskDelete(NULL);
}
